version: "3"
services:
  tcpnginx:
    image: nginx:alpine
    networks:
      - traefik-tcp
    volumes:
      - "./tcp:/usr/share/nginx/html:ro"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.tcpnginx.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.tcpnginx.tls=false"
        - "traefik.tcp.routers.tcpnginx.service=tcpnginx"
        - "traefik.tcp.services.tcpnginx.loadbalancer.server.port=80"

networks:
  traefik-tcp:
    external: true
