version: '3'

services:
  traefik:
    image: traefik:v2.0
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-tcp"
      - "--entrypoints.web.address=:81"
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
    ports:
      - 81:81
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-tcp
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-tcp:
    external: true